### ISSUE TITLE
Qiniu cdn with ua protection test error

### ISSUE THREAD

**Issue by RikkaBlue** [cloudorangeblue/fake-ban-steal-link_koa#1]
*Internal Server Error*

**Comment by cloudorangeblue** [comment]
代码问题 
初步判定错误代码在 `/src/routes/index.js`文件中
暂时不知道为何会出现这样的问题，我在发起请求的时候时加入了错误捕捉，正常情况下错误会被捕捉，不应该直接抛出导致Internal Server Error。
错误调查中...

**Comment by cloudorangeblue** [comment]
问题在于axios在Windows下使用proxy可以正常代理请求，在Ubuntu下axios直接通过proxy ip访问proxy局域网内的数据，不知道原因。
这也是为什么之前访问一个存在的地址，axios却提示404的现象惹。
